"""empty message

Revision ID: b07b2694bf98
Revises: 9a16419658ec
Create Date: 2022-09-30 16:22:16.625636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07b2694bf98'
down_revision = '9a16419658ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.LargeBinary(), nullable=True))
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
